server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 1000
      min-spare: 30
  port: 8080
  servlet:
    context-path: /
    session:
      cookie:
        http-only: true
  shutdown: graceful

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  typeAliasesPackage: ling.yang.*.entity
  global-config:
    db-config:
      id-type: AUTO
      logic-delete-value: 1
      logic-not-delete-value: 0
    banner: false
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
  configuration-properties:
    prefix:
    blobType: BLOB
    boolValue: TRUE
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myshop?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: myshop
    password: myshopmyshop
    hikari:
      connection-timeout: 30000
      minimum-idle: 2
      maximum-pool-size: 10
      auto-commit: true
      idle-timeout: 600000
      max-lifetime: 1200000
      connection-test-query: SELECT 1
      pool-name: MyShopHikariCP
logging:
  level:
   ling.yang.myshop.mapper: debug
