spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testmyshop?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    data: classpath:/test-data.sql
    username: root
    password: hNc_s25ZhZFtMMiddhzeUHrTK
